// T3 Crash Shield (Barrier) golden-CBOR regression.
//
// T3 needs NO new composer — buildUnderwriteParts already supports
// riskClass:'Barrier'. This suite LOCKS the Barrier underwrite path byte-for-byte
// for the three canonical crash-shield feeds:
//
//   ADA   → FEEDS.ADA_USD (f0f14cd0…342301)  — AegisSelf publisher feed
//   iBTC  → FEEDS.BTC_USD (99e8fe4f…2163b3)  — AegisSelf publisher feed
//   iETH  → FEEDS.ETH_USD (a8c5354a…95f9c)   — AegisSelf publisher feed
//
// Each asserts the exact policy inline datum (with that feed's oracle NFT +
// oracleProvider AegisSelf + riskClass Barrier), the pool continuation datum,
// the pool/marker redeemers, and validity. The three policy datums differ ONLY
// in the oracle-NFT field, proving the feed wiring is the single moving part.
//
// The mainnet AegisSelf spot feeds (ADA/BTC/ETH) are the canonical publisher
// NFTs (constants.mainnet.AEGIS_PUBLISHER_CANONICAL_NFTS), so the correct
// oracleProvider for every one of them is 'AegisSelf' (the composer default) and
// the oracle NFT is the feed's policyId. A Barrier policy REQUIRES an oracle ref
// input on chain — `references.oracleRequired` must be true.
//
// iSOL / SOL is intentionally ABSENT: there is no canonical mainnet SOL feed in
// FEEDS or AEGIS_PUBLISHER_CANONICAL_NFTS (iSOL exists only as an Indigo CDP
// mock with a placeholder "MOCK_ISOL_ORACLE", not a published NFT). It is OUT OF
// SCOPE until a real feed is published — see the dedicated test below. We do NOT
// invent a policy id.

import { describe, it, expect } from 'vitest';
import { buildUnderwriteParts } from '../compose';
import { FEEDS, findFeedByPolicyId } from '../feeds';
import { quoteForPosition } from '../quote';
import { MIN_STRIKE_DISTANCE_BPS } from '../floor_table';
import { decodePoolRedeemer, decodeMarkerRedeemer, hexToBytes, bytesToHex } from '../cbor';

// ── Mainnet V4 bindings (release/mainnet.json) — same frozen manifest the T1
//    depeg golden uses, so the two suites share a single source of truth. ─────
const POOL_VALIDATOR_HASH = 'c08edc7fd1b082e92c97a9aebcf63a647688ec8092581646d6ff667f';
const POLICY_VALIDATOR_HASH = '1677dc4a0089047ee3136ca7bea0f36e49d6707468809f4f7d46dfb7';
const MARKER_HASH = 'd9d24db4e4dabdc1af6a568a4ecd691b81fae891afd70eb6cabc51e7';
const POOL_NFT_POLICY = '9a649b75a85f0088eb68c1b72c3529b41f874fcdc603031a1444abb3';
const LP_TOKEN_HASH = '5cb64f303517777710d28db50ad3be4bb9feda5f66d0fbffa68e212b';
const POLICY_ADDR = 'addr1wyt80hz2qzysglhrzdk2004q7dhyn4nsw35gp86004rdldcnuy3ev';
const POOL_ADDR = 'addr1w8qgahrl6xcg96fvj756a08k8fj8dz8vszf9s9jx6mlkvlclvfgtr';
const TEAM_ADDR = 'addr1q9s6m9d8yedfcf53yhq5j5zsg0s58wpzamwexrxpfelgz2wgk0s9l9fqc93tyc8zu4z7hp9dlska2kew9trdg8nscjcq3sk5s3';
const MARKER_NAME_HEX = '41454749535f504f4c494359'; // "AEGIS_POLICY"

function mainnetBindings() {
  return {
    network: 'mainnet' as const,
    policyValidatorHash: POLICY_VALIDATOR_HASH,
    poolValidatorHash: POOL_VALIDATOR_HASH,
    poolAddress: POOL_ADDR,
    poolNftPolicyId: POOL_NFT_POLICY,
    poolNftAssetNameHex: bytesToHex(new TextEncoder().encode('AEGIS_POOL_V4')),
    markerPolicyId: MARKER_HASH,
    teamAddress: TEAM_ADDR,
  };
}

function pool() {
  return {
    utxoRef: { txHash: 'c5f488034e869b1404c505ed797caa49905943641693422b1e19e2a3919ee297', index: 0 },
    lovelace: 100_000_000_000n,
    datum: {
      totalLiquidity: 100_000_000_000n,
      activeCoverage: 1_000_000_000n,
      lpTokenPolicy: hexToBytes(LP_TOKEN_HASH),
      protocolFeeBps: 200n,
      poolNft: hexToBytes(POOL_NFT_POLICY),
      lpSupply: 50_000_000_000n,
    },
  };
}

// Pinned inputs shared by all three feeds (so the ONLY datum delta is the oracle
// NFT). strike $0.51, spot $1.00 → d = 49% (deep, well past the 15% minimum);
// 2000 ADA cover, premium just under cover (clears the d49/30d floor; 50x ratio
// holds). Times + policy_id pinned for byte-exact reproduction.
const INSURED = 'ae725d4765d908f114552f53422317cbef8c42698fc2b67e45466931';
const POLICY_ID = '739cce791c33ec85aa531b119da20f9624eaf7a4470e10e3282a3f65';
const STRIKE = 510_000n;
const SPOT = 1_000_000n;
const COVERAGE = 2_000_000_000n;
const PREMIUM = 2_000_000_000n - 1n;
const START = 1_750_000_000_000n;
const EXPIRY = 1_750_000_000_000n + 30n * 86_400_000n;

function barrierParts(oraclePolicyId: string) {
  return buildUnderwriteParts({
    bindings: mainnetBindings(),
    pool: pool(),
    insuredPkh: INSURED,
    strikePriceScaled: STRIKE,
    spotPriceScaled: SPOT,
    coverageLovelace: COVERAGE,
    premiumLovelace: PREMIUM,
    durationDays: 30,
    oraclePolicyId,
    oracleProvider: 'AegisSelf',
    riskClass: 'Barrier',
    policyId: POLICY_ID,
    startTimeMs: START,
    expiryTimeMs: EXPIRY,
  });
}

// The frozen golden policy datums (generated by the SDK encoder, then pinned).
// Identical except the 9th byte-string field (581c<oracle NFT>):
//   provider d87b80 = Constr 2 = AegisSelf; partner d87a80 = None; share 00;
//   risk d87980 = Constr 0 = Barrier.
const POLICY_DATUM: Record<string, string> = {
  ADA_USD:
    'd8799f581c739cce791c33ec85aa531b119da20f9624eaf7a4470e10e3282a3f65581cae725d4765d908f114552f53422317cbef8c42698fc2b67e454669311a0007c8301a773594001a773593ff1b000001977420dc001b000001980e9fa400581cf0f14cd0dd1cae52398360e3e4001375000032cb392cb3efeb342301581cc08edc7fd1b082e92c97a9aebcf63a647688ec8092581646d6ff667f581c9a649b75a85f0088eb68c1b72c3529b41f874fcdc603031a1444abb3d87b80d87a8000d87980ff',
  BTC_USD:
    'd8799f581c739cce791c33ec85aa531b119da20f9624eaf7a4470e10e3282a3f65581cae725d4765d908f114552f53422317cbef8c42698fc2b67e454669311a0007c8301a773594001a773593ff1b000001977420dc001b000001980e9fa400581c99e8fe4f9d2a4a85f5e3f20d37b10048ce54e4a03e56d9fd492163b3581cc08edc7fd1b082e92c97a9aebcf63a647688ec8092581646d6ff667f581c9a649b75a85f0088eb68c1b72c3529b41f874fcdc603031a1444abb3d87b80d87a8000d87980ff',
  ETH_USD:
    'd8799f581c739cce791c33ec85aa531b119da20f9624eaf7a4470e10e3282a3f65581cae725d4765d908f114552f53422317cbef8c42698fc2b67e454669311a0007c8301a773594001a773593ff1b000001977420dc001b000001980e9fa400581ca8c5354a4813f2b3f60836839b8842a9422186f4f15511790ec95f9c581cc08edc7fd1b082e92c97a9aebcf63a647688ec8092581646d6ff667f581c9a649b75a85f0088eb68c1b72c3529b41f874fcdc603031a1444abb3d87b80d87a8000d87980ff',
};

// Pool continuation + redeemers are feed-independent (same coverage/premium).
const POOL_DATUM_GOLDEN =
  'd8799f1b00000017bd4a22001ab2d05e00581c5cb64f303517777710d28db50ad3be4bb9feda5f66d0fbffa68e212b18c8581c9a649b75a85f0088eb68c1b72c3529b41f874fcdc603031a1444abb31b0000000ba43b7400ff';
const POOL_REDEEMER_GOLDEN = 'd8799f1a773594001a773593ffff';
const MARKER_REDEEMER_GOLDEN = 'd8799f01ff';

const FEED_CASES: { name: string; feed: typeof FEEDS.ADA_USD }[] = [
  { name: 'ADA (FEEDS.ADA_USD)', feed: FEEDS.ADA_USD },
  { name: 'iBTC (FEEDS.BTC_USD)', feed: FEEDS.BTC_USD },
  { name: 'iETH (FEEDS.ETH_USD)', feed: FEEDS.ETH_USD },
];

describe.each(FEED_CASES)('T3 Crash Shield Barrier golden — $name', ({ feed }) => {
  const parts = barrierParts(feed.policyId);

  it('is insurable and carries the Barrier risk class', () => {
    expect(parts.insurable).toBe(true);
    expect(parts.policyDatum.riskClass).toBe('Barrier');
  });

  it('pins the policy to this feed NFT with the AegisSelf provider', () => {
    // The feed registry resolves the right NFT, and the publisher feed is
    // AegisSelf-published (constants.mainnet AEGIS_PUBLISHER_CANONICAL_NFTS).
    expect(feed.kind).toBe('spot');
    expect(feed.riskClass).toBe('Barrier');
    expect(findFeedByPolicyId(feed.policyId)).toBe(feed);
    expect(bytesToHex(parts.policyDatum.oracleNft)).toBe(feed.policyId);
    expect(parts.policyDatum.oracleProvider).toBe('AegisSelf');
  });

  it('GOLDEN: policy output datum CBOR (byte-for-byte, only the oracle NFT varies)', () => {
    expect(parts.policyOutput.inlineDatumCbor).toBe(POLICY_DATUM[feed.symbol]);
    // Provider AegisSelf = Constr 2 (tag 123 → d87b80); Barrier = Constr 0 (d87980).
    expect(parts.policyOutput.inlineDatumCbor).toContain('d87b80'); // AegisSelf
    expect(parts.policyOutput.inlineDatumCbor.endsWith('d87a8000d87980ff')).toBe(true); // None, 0, Barrier
  });

  it('places coverage + 1 marker at the policy script address', () => {
    expect(parts.policyOutput.address).toBe(POLICY_ADDR);
    expect(parts.policyOutput.lovelace).toBe(COVERAGE);
    expect(parts.policyOutput.marker).toEqual({ policyId: MARKER_HASH, assetNameHex: MARKER_NAME_HEX, quantity: 1n });
  });

  it('GOLDEN: pool continuation datum CBOR (total += net_growth, active += coverage)', () => {
    expect(parts.poolOutput.address).toBe(POOL_ADDR);
    expect(parts.poolOutput.inlineDatumCbor).toBe(POOL_DATUM_GOLDEN);
    expect(parts.poolOutput.poolNft).toEqual({
      policyId: POOL_NFT_POLICY,
      assetNameHex: bytesToHex(new TextEncoder().encode('AEGIS_POOL_V4')),
      quantity: 1n,
    });
  });

  it('GOLDEN: pool redeemer = Underwrite{coverage, premium} + marker MintMarkers{1}', () => {
    expect(parts.poolRedeemerCbor).toBe(POOL_REDEEMER_GOLDEN);
    expect(decodePoolRedeemer(hexToBytes(parts.poolRedeemerCbor))).toEqual({
      kind: 'Underwrite',
      coverage: COVERAGE,
      premium: PREMIUM,
    });
    expect(parts.mint.redeemerCbor).toBe(MARKER_REDEEMER_GOLDEN);
    expect(decodeMarkerRedeemer(hexToBytes(parts.mint.redeemerCbor))).toEqual({ kind: 'MintMarkers', count: 1 });
  });

  it('a Barrier policy REQUIRES the oracle reference input on chain', () => {
    expect(parts.references.oracleRequired).toBe(true);
  });

  it('validity: start + 30d expiry are exactly the pinned times', () => {
    expect(parts.validity.startTimeMs).toBe(START);
    expect(parts.validity.expiryTimeMs).toBe(EXPIRY);
  });
});

describe('T3 Barrier golden — the three policy datums differ ONLY in the oracle NFT', () => {
  it('ADA / iBTC / iETH datums are byte-identical except the 581c<NFT> field', () => {
    const ada = POLICY_DATUM.ADA_USD;
    const btc = POLICY_DATUM.BTC_USD;
    const eth = POLICY_DATUM.ETH_USD;
    // Replace each feed NFT with a placeholder; the remaining bytes must match.
    const norm = (s: string, nft: string) => s.replace(nft, '<NFT>');
    expect(norm(ada, FEEDS.ADA_USD.policyId)).toBe(norm(btc, FEEDS.BTC_USD.policyId));
    expect(norm(btc, FEEDS.BTC_USD.policyId)).toBe(norm(eth, FEEDS.ETH_USD.policyId));
  });
});

// ───────────────────────────────────────────────────────────────────────────
// quoteForPosition — Barrier insurability boundary (strike ≥15% below spot).
// ───────────────────────────────────────────────────────────────────────────

describe('quoteForPosition Barrier — 15%-below-spot insurable boundary', () => {
  const SPOT_1 = 1_000_000n; // $1.00
  const base = {
    riskClass: 'Barrier' as const,
    coverageLovelace: 2_000_000_000n,
    spotPriceScaled: SPOT_1,
    durationDays: 30,
  };

  it('exactly 15% below spot PASSES (dBps == MIN_STRIKE_DISTANCE_BPS)', () => {
    // strike $0.85 → d = (1.00-0.85)/1.00 = 15.00% = 1500 bps = the minimum.
    const v = quoteForPosition({ ...base, strikePriceScaled: 850_000n });
    expect(v.dBps).toBe(MIN_STRIKE_DISTANCE_BPS); // 1500
    expect(v.insurable).toBe(true);
    expect(v.reasonCode).toBeNull();
  });

  it('14.9% below spot is REJECTED with BELOW_MIN_STRIKE_DISTANCE', () => {
    // strike $0.851 → d = 14.9% = 1490 bps < 1500.
    const v = quoteForPosition({ ...base, strikePriceScaled: 851_000n });
    expect(v.dBps).toBe(1490);
    expect(v.insurable).toBe(false);
    expect(v.reasonCode).toBe('BELOW_MIN_STRIKE_DISTANCE');
    expect(v.reason).toMatch(/15% minimum|deeper strike/i);
  });

  it('one bps inside the boundary (14.99% via $0.8501) is still rejected', () => {
    // strike $0.8501 → d = 1499 bps < 1500 (boundary is closed at 1500).
    const v = quoteForPosition({ ...base, strikePriceScaled: 850_100n });
    expect(v.dBps).toBe(1499);
    expect(v.insurable).toBe(false);
    expect(v.reasonCode).toBe('BELOW_MIN_STRIKE_DISTANCE');
  });

  it('a strike AT or ABOVE spot is rejected as STRIKE_NOT_BELOW_SPOT', () => {
    const atSpot = quoteForPosition({ ...base, strikePriceScaled: SPOT_1 });
    expect(atSpot.insurable).toBe(false);
    expect(atSpot.reasonCode).toBe('STRIKE_NOT_BELOW_SPOT');

    const aboveSpot = quoteForPosition({ ...base, strikePriceScaled: 1_100_000n });
    expect(aboveSpot.insurable).toBe(false);
    expect(aboveSpot.reasonCode).toBe('STRIKE_NOT_BELOW_SPOT');
  });
});

// ───────────────────────────────────────────────────────────────────────────
// iSOL / SOL — OUT OF SCOPE (no published feed). Do NOT invent a policy id.
// ───────────────────────────────────────────────────────────────────────────

describe('T3 Crash Shield — iSOL / SOL is out of scope (no canonical feed)', () => {
  it('there is NO SOL/iSOL feed in the canonical FEEDS registry', () => {
    // iSOL exists only as an Indigo CDP MOCK asset (offchain/scripts/
    // init_indigo_mock.py: "iSOL" → "MOCK_ISOL_ORACLE"), NOT a published mainnet
    // oracle NFT. Until a real SOL/USD feed is minted into
    // AEGIS_PUBLISHER_CANONICAL_NFTS, iSOL crash-shield coverage cannot be
    // composed — and this SDK will not fabricate a policy id for it.
    const symbols = Object.keys(FEEDS);
    expect(symbols.some((s) => /SOL/i.test(s))).toBe(false);
    expect(FEEDS.SOL_USD).toBeUndefined();
    expect(FEEDS.ISOL_USD).toBeUndefined();
  });
});
