// Originally auto-generated from release/mainnet.json
// (release_commit=45206a8b5bba90f1ceaf899d29e78e4b5a8847a7, network=mainnet,
// compiler v1.1.22+39d6b04, frozen 2026-07-08T02:59:32Z). That upstream
// manifest is now STALE: it carries the old defective pool family (observer
// defect). This file has been manually repointed to the 2026-07-10 rotated
// V7 family (rotation proof tx
// 17b64a52fd5531ee9f73c104f7f5b34c1e4de7cc25d0ae017acb8b4e66ff13ef).
//
// The upstream release/mainnet.json and scripts/sync_sdk_constants_from_manifest.py
// in the contracts repo must be regenerated by the Aegis owners to match the
// rotated family before this file is auto-generated again (those files are not
// part of this SDK repo).


export const AEGIS_NETWORK = 'mainnet';
export const AEGIS_POOL_ADDRESS = 'addr1w8x2ts0jccv4ellphq44x9qhheprkz3ljxm7ws0q8j7xelcj85sg4';
export const AEGIS_POOL_NFT_POLICY_ID = '9cf48b68374e539babe1bd583151868d031c37a83443ee58b8b2571a';
export const AEGIS_POOL_NFT_ASSET_NAME = 'AEGIS_POOL_V7';

// Applied script hashes (live on-chain).
export const AEGIS_POLICY_VALIDATOR_HASH = 'f2557118860f37dfd6b3fa4a7c5f1a593761d3e1391418efaeb8cf2c';
export const AEGIS_POOL_VALIDATOR_HASH = 'cca5c1f2c6195cffe1b82b531417be423b0a3f91b7e741e03cbc6cff';
export const AEGIS_POLICY_MARKER_HASH = '7778a648610ee4e87004c867fd40c277d159139d635453fce270f0ab';
export const AEGIS_LP_TOKEN_HASH = 'ad155127c7022f435ec0b1be0992de0f72200c9a120f91a70fba2656';

// Reference UTxOs (empty when ref script not yet published).
export const AEGIS_POLICY_REF_TX = '97e95a829240c7ea5612f6aa353fc0efe3e93776c02c07b8bbfebd4d6475e09c';
export const AEGIS_POLICY_REF_IDX = 0;
export const AEGIS_POLICY_REF_UTXO = '97e95a829240c7ea5612f6aa353fc0efe3e93776c02c07b8bbfebd4d6475e09c#0';
export const AEGIS_POOL_REF_TX = '971bd46c6c97372dde752eb4222afbc237278de8d39a6efd4af85ac1933d487f';
export const AEGIS_POOL_REF_IDX = 0;
export const AEGIS_POOL_REF_UTXO = '971bd46c6c97372dde752eb4222afbc237278de8d39a6efd4af85ac1933d487f#0';
export const AEGIS_MARKER_REF_TX = '239c25639661589b8943bba62558d1e293ef944e789e7ea03634987ad68b943f';
export const AEGIS_MARKER_REF_IDX = 0;
export const AEGIS_MARKER_REF_UTXO = '239c25639661589b8943bba62558d1e293ef944e789e7ea03634987ad68b943f#0';
export const AEGIS_LP_REF_TX = 'bf5cd5c2c33f33f546f39826ea36aa9d40bc3158aee293546d1e4163d85f6bc3';
export const AEGIS_LP_REF_IDX = 0;
export const AEGIS_LP_REF_UTXO = 'bf5cd5c2c33f33f546f39826ea36aa9d40bc3158aee293546d1e4163d85f6bc3#0';

// Economic constants (BigInt-typed; matches on-chain types.ak).
export const AEGIS_TEAM_ADDRESS = 'addr1q9s6m9d8yedfcf53yhq5j5zsg0s58wpzamwexrxpfelgz2wgk0s9l9fqc93tyc8zu4z7hp9dlska2kew9trdg8nscjcq3sk5s3';
export const AEGIS_MIN_PREMIUM = 20000000n;
export const AEGIS_TREASURY_SHARE_BPS = 2500n;

// Publisher.
export const AEGIS_PUBLISHER_VKH = 'bb09f43245759995440388db9ef3f8a614246e8da1dd9bd053261347';
export const AEGIS_PUBLISHER_CANONICAL_NFTS: readonly string[] = ['f0f14cd0dd1cae52398360e3e4001375000032cb392cb3efeb342301.', '99e8fe4f9d2a4a85f5e3f20d37b10048ce54e4a03e56d9fd492163b3.', 'a8c5354a4813f2b3f60836839b8842a9422186f4f15511790ec95f9c.', 'a8231f0c10b514659fd590f6ee7420acf4e145cce36909a7f5fe1c5e.', '82a324a3de0be7bc9c4b8450db5350cf0479fa1393eb8eee2481c652.', 'f6458f3b7a6b2027fe89c39a622956336ec3253b7d65971f0cb64b02.', 'c2f62874c860e1fc87bae0043066e551153f30fcc5d9944a370e8f8d.', 'f4e78f3636248838c2d5c6578062cfb78f385482b0078de7aff5cc3b.', '68a1b0c1dab38159e9aae015c2c577a8da3661f921410dbad6276b2f.', '47c16934540cdead6045f947b1a7fd4b910bc0352a269b11800d0bed.', 'b99998ba0353f47137fb9499da624b63a855d60719d4902777312439.'] as const;

// Oracles.
export const AEGIS_CHARLI3_ADA_USD_NFT = '08c56c0fa73748a23c3bc1d9e6a60a4187416fc4ff8fe3475506990e.4f7261636c6546656564';
export const AEGIS_ORCFAX_FSP_HASH = '8793893b5dda6a513ba63c80e9d7b2d4f108060c11979bfc7d863ff0';
